### ISSUE TITLE
Need More Details

### ISSUE THREAD

**Issue by praveenkumar66** [JesseFarebro/android-mqtt#7]
Hi Jesse,
How can i handle the response messages from receiver(i am a sender)..messageArrived method will have all the responses (or) it will have only themessage which has been sent by user atlast . . .if u have any flow diagram for mqtt working actions for android pls provide  ..  ..

**Comment by JesseFarebro** [comment]
So once you send a message the function ```deliveryComplete``` gets called on success. If you are subscribed to a topic those messages will be received through the ```messageArrived``` function. 

The documentation is straight out of the Java Paho client for the MqttCallback interface and can be found at [this](http://www.eclipse.org/paho/files/javadoc/index.html) link.

As per a flow diagram if you are having trouble with the MQTT flow take a look [here](https://www.rabbitmq.com/tutorials/tutorial-three-python.html). Although that link is for AMQP the same overall concept of publish and subscribing can be drawn for MQTT. RabbitMQ has useful diagrams.

Hope that helps.

**Comment by praveenkumar66** [comment]
Great Thanks for ur comments.i will look into the link which u have provide and come back to you..

**Comment by praveenkumar66** [comment]
This is my code . .     

@Override
    public void onCreate() {
        super.onCreate();
        try {
            connect();
        } catch (MqttException e) {
            e.printStackTrace();
        }
    }

    private void connect() throws MqttException{
        SharedPreferences prefs = this.getSharedPreferences("default", MODE_PRIVATE);

        if (prefs.contains(CLIENT_ID) == false) {
            String clientId = java.util.UUID.randomUUID().toString();
            SharedPreferences.Editor editor = prefs.edit();
            editor.putString(CLIENT_ID, clientId);
            editor.commit();
        }

        String clientId = prefs.getString(CLIENT_ID, "");
        String server = "192.168.2.15";
        String port = "1883";
        boolean cleanSession = false;

        String uri = "tcp://" + server + ":" + port;

        mClient = new MqttAndroidClient(this, uri, clientId);
        MqttConnectOptions conOpt = new MqttConnectOptions();

        conOpt.setCleanSession(cleanSession);
        conOpt.setConnectionTimeout(10000);
        conOpt.setKeepAliveInterval(600000);
        conOpt.setUserName("admin");
        conOpt.setPassword("admin".toCharArray());

        mClient.setCallback(this);
        mClient.setTraceCallback(this);

        mIsConnecting = true;
        mClient.connect(conOpt, null, this);
    }
    public void sendMessage(String message) {
       // String topic = "Topic/qGKMJ:d5jvG:c4f4940c-2947-41e9-9a04-930422a5e5ab";
        String topic = "topic";
        String textToSend = message;
        int qos = 2;
        boolean retained = false;
        String[] args = new String[2];
        args[0] = textToSend;
        args[1] = topic+";qos:"+qos+";retained:"+retained;

        try {
            mClient.publish(topic, textToSend.getBytes(), qos, retained, null, this);
        }
        catch (MqttSecurityException e) {
            e.printStackTrace();
        }
        catch (MqttException e) {
            e.printStackTrace();
        }
    }

    @Override
    public void onSuccess(IMqttToken iMqttToken) {
        if(mIsConnecting) {
            mIsConnecting = false;
            subscribe();
        }
    }

    private void subscribe()
    {
        String topic = "topic";
        int qos = 0;

        try {
            String[] topics = new String[1];
            topics[0] = topic;
            getClient().subscribe(topic, qos, null, this);
        }
        catch (MqttSecurityException e) {
            e.printStackTrace();
        }
        catch (MqttException e) {
            e.printStackTrace();
        }
    }

    @Override
    public void onFailure(IMqttToken iMqttToken, Throwable throwable) {
        Log.e(ChatService.TAG, "something went wrong: " + throwable);
    }

    @Override
    public void connectionLost(Throwable throwable) {
        Log.e(ChatService.TAG, "something went wrong: " + throwable);
    }

    @Override
    public void messageArrived(String s, MqttMessage mqttMessage) throws Exception {
        Log.i(TAG, mqttMessage.toString());
        mBinder.messageArrived(mqttMessage.toString());
    }

    @Override
    public void deliveryComplete(IMqttDeliveryToken iMqttDeliveryToken) {

    }

    @Override
    public void traceDebug(String source, String message) {

    }

    @Override
    public void traceError(String source, String message) {

    }

    @Override
    public void traceException(String source, String message, Exception e) {
        e.printStackTrace();
    }

    @Override
    public IBinder onBind(Intent intent) {
        return mBinder;
    }
    public MqttAndroidClient getClient() {
        return mClient;
    }
i have posted the action step by step ,which i have been doing now . .

1)First i have connected to the active mq server using Mqtt client mClient.connect() inside connect method

2)After connection was success,i can able to send message to the server by using mClient.publish() method in sendMessage() method.

3)my message got displayed in ActiveMq server Messages Enqueued List with my topic which have created statically . . . 

4)After i published my message , i will implement IMqttActionListener  callbacks onSuccess and onFailure to check my message was created .In onSuccess() i have called subscibe() method ..Here i have big question . .am i doing actions correctly or what . .when shud i subscribe to the messages which will be sent to me ....

Please help me to get clear on this . ..also i do not no what retain and qos exactly do in this process .. .  . .

**Comment by praveenkumar66** [comment]
I have integrate this code https://eclipse.org/paho/clients/android/sample/ in my studio and tested . . .
the flow was 
Me : connect to server ----> subscribe the topic ----> publish to the topic -----> notified by the app

User2 (Server Side) : connect to the topic ----> read the message which i have sent ---> reply top that message ..

me : i will be received notification of the message replied by the server team . . .

how i got this reply mesage ...(i.e) in code ,i cnt find where they handle this response ....
